from __future__ import annotations

from dataclasses import dataclass

import psycopg

from quant_system.config import PostgresConfig, SystemConfig


POSTGRES_SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS experiments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        profile_name VARCHAR(255),
        description TEXT,
        broker_symbol VARCHAR(64),
        data_symbol VARCHAR(64),
        ending_equity DOUBLE PRECISION,
        realized_pnl DOUBLE PRECISION,
        trades INTEGER,
        closed_trades INTEGER,
        win_rate_pct DOUBLE PRECISION,
        profit_factor DOUBLE PRECISION,
        max_drawdown_pct DOUBLE PRECISION,
        total_costs DOUBLE PRECISION,
        ftmo_passed BOOLEAN,
        ftmo_reasons TEXT,
        optimized_agents_json TEXT,
        local_summary TEXT,
        ai_summary TEXT,
        next_experiments_json TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS experiment_artifacts (
        experiment_id BIGINT,
        trade_log TEXT,
        trade_analysis TEXT,
        signal_log TEXT,
        signal_analysis TEXT,
        shadow_log TEXT,
        shadow_analysis TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS symbol_research_runs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        profile_name VARCHAR(255),
        data_symbol VARCHAR(64),
        broker_symbol VARCHAR(64),
        data_source VARCHAR(64),
        recommended_names_json TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS symbol_research_candidates (
        symbol_research_run_id BIGINT,
        profile_name VARCHAR(255),
        candidate_name TEXT,
        description TEXT,
        archetype VARCHAR(128),
        code_path TEXT,
        realized_pnl DOUBLE PRECISION,
        closed_trades INTEGER,
        win_rate_pct DOUBLE PRECISION,
        profit_factor DOUBLE PRECISION,
        max_drawdown_pct DOUBLE PRECISION,
        total_costs DOUBLE PRECISION,
        train_pnl DOUBLE PRECISION,
        validation_pnl DOUBLE PRECISION,
        validation_profit_factor DOUBLE PRECISION,
        validation_closed_trades INTEGER,
        test_pnl DOUBLE PRECISION,
        test_profit_factor DOUBLE PRECISION,
        test_closed_trades INTEGER,
        expectancy DOUBLE PRECISION,
        sharpe_ratio DOUBLE PRECISION,
        sortino_ratio DOUBLE PRECISION,
        calmar_ratio DOUBLE PRECISION,
        avg_win DOUBLE PRECISION,
        avg_loss DOUBLE PRECISION,
        payoff_ratio DOUBLE PRECISION,
        avg_hold_bars DOUBLE PRECISION,
        best_trade_share_pct DOUBLE PRECISION,
        equity_new_high_share_pct DOUBLE PRECISION,
        max_consecutive_losses INTEGER,
        equity_quality_score DOUBLE PRECISION,
        dominant_exit VARCHAR(128),
        dominant_exit_share_pct DOUBLE PRECISION,
        walk_forward_windows INTEGER,
        walk_forward_pass_rate_pct DOUBLE PRECISION,
        walk_forward_avg_validation_pnl DOUBLE PRECISION,
        walk_forward_avg_test_pnl DOUBLE PRECISION,
        walk_forward_avg_validation_pf DOUBLE PRECISION,
        walk_forward_avg_test_pf DOUBLE PRECISION,
        component_count INTEGER,
        combo_outperformance_score DOUBLE PRECISION,
        combo_trade_overlap_pct DOUBLE PRECISION,
        best_regime VARCHAR(128),
        best_regime_pnl DOUBLE PRECISION,
        worst_regime VARCHAR(128),
        worst_regime_pnl DOUBLE PRECISION,
        dominant_regime_share_pct DOUBLE PRECISION,
        regime_stability_score DOUBLE PRECISION,
        regime_loss_ratio DOUBLE PRECISION,
        regime_trade_count_by_label TEXT,
        regime_pnl_by_label TEXT,
        regime_pf_by_label TEXT,
        regime_win_rate_by_label TEXT,
        variant_label VARCHAR(128),
        timeframe_label VARCHAR(64),
        session_label VARCHAR(64),
        regime_filter_label VARCHAR(128),
        mc_simulations INTEGER,
        mc_pnl_median DOUBLE PRECISION,
        mc_pnl_p05 DOUBLE PRECISION,
        mc_pnl_p95 DOUBLE PRECISION,
        mc_max_drawdown_pct_median DOUBLE PRECISION,
        mc_max_drawdown_pct_p95 DOUBLE PRECISION,
        mc_loss_probability_pct DOUBLE PRECISION,
        execution_overrides_json TEXT,
        recommended BOOLEAN
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS symbol_execution_sets (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        symbol_research_run_id BIGINT,
        profile_name VARCHAR(255),
        broker_symbol VARCHAR(64),
        execution_validation_summary TEXT,
        symbol_status VARCHAR(64),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS symbol_execution_set_items (
        execution_set_id BIGINT,
        candidate_name TEXT,
        promotion_tier VARCHAR(64),
        policy_summary TEXT,
        code_path TEXT,
        variant_label VARCHAR(128),
        regime_filter_label VARCHAR(128),
        execution_overrides_json TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS mt5_fill_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        broker_symbol VARCHAR(64) NOT NULL,
        requested_symbol VARCHAR(64),
        side VARCHAR(16),
        quantity DOUBLE PRECISION,
        requested_price DOUBLE PRECISION,
        filled_price DOUBLE PRECISION,
        bid DOUBLE PRECISION,
        ask DOUBLE PRECISION,
        spread_points DOUBLE PRECISION,
        slippage_points DOUBLE PRECISION,
        slippage_bps DOUBLE PRECISION,
        costs DOUBLE PRECISION,
        reason TEXT,
        confidence DOUBLE PRECISION,
        metadata_json TEXT,
        magic_number BIGINT,
        comment TEXT,
        position_ticket BIGINT
    )
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS event_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS requested_symbol VARCHAR(64)
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS side VARCHAR(16)
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS quantity DOUBLE PRECISION
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS requested_price DOUBLE PRECISION
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS fill_price DOUBLE PRECISION
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS bid DOUBLE PRECISION
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS ask DOUBLE PRECISION
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS spread_points DOUBLE PRECISION
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS slippage_points DOUBLE PRECISION
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS slippage_bps DOUBLE PRECISION
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS costs DOUBLE PRECISION
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS reason TEXT
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS confidence DOUBLE PRECISION
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS metadata_json TEXT
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS magic_number BIGINT
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS comment TEXT
    """,
    """
    ALTER TABLE mt5_fill_events ADD COLUMN IF NOT EXISTS position_ticket BIGINT
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_symbol_research_runs_profile_created
    ON symbol_research_runs (profile_name, created_at DESC)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_symbol_research_candidates_run
    ON symbol_research_candidates (symbol_research_run_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_mt5_fill_events_symbol_created
    ON mt5_fill_events (broker_symbol, event_timestamp DESC)
    """,
)


@dataclass(slots=True)
class PostgresBootstrapResult:
    dsn_without_password: str
    database: str
    host: str
    port: int


def _postgres_config(config: SystemConfig | PostgresConfig | None) -> PostgresConfig:
    if config is None:
        return SystemConfig().postgres
    if isinstance(config, PostgresConfig):
        return config
    return config.postgres


def connect_postgres(
    config: SystemConfig | PostgresConfig | None = None,
    *,
    include_database: bool = True,
    database_override: str | None = None,
    autocommit: bool = False,
):
    postgres = _postgres_config(config)
    dsn = postgres.dsn(include_database=include_database)
    if database_override:
        dsn = postgres.dsn(include_database=False) + f"&dbname={database_override}"
    connection = psycopg.connect(dsn, autocommit=autocommit)
    return connection


def ensure_postgres_database(config: SystemConfig | PostgresConfig | None = None) -> None:
    postgres = _postgres_config(config)
    with connect_postgres(postgres, include_database=False, database_override="postgres", autocommit=True) as connection:
        with connection.cursor() as cursor:
            cursor.execute("SELECT 1 FROM pg_database WHERE datname = %s", [postgres.database])
            exists = cursor.fetchone() is not None
            if not exists:
                cursor.execute(f'CREATE DATABASE "{postgres.database}"')


def initialize_postgres_schema(config: SystemConfig | PostgresConfig | None = None) -> PostgresBootstrapResult:
    postgres = _postgres_config(config)
    ensure_postgres_database(postgres)
    with connect_postgres(postgres, autocommit=True) as connection:
        with connection.cursor() as cursor:
            for statement in POSTGRES_SCHEMA_STATEMENTS:
                cursor.execute(statement)
    return PostgresBootstrapResult(
        dsn_without_password=postgres.dsn(include_password=False),
        database=postgres.database,
        host=postgres.host,
        port=postgres.port,
    )


def test_postgres_connection(config: SystemConfig | PostgresConfig | None = None) -> dict[str, object]:
    postgres = _postgres_config(config)
    with connect_postgres(postgres, autocommit=True) as connection:
        with connection.cursor() as cursor:
            cursor.execute("SELECT current_database(), current_user, version()")
            row = cursor.fetchone()
    return {
        "database": row[0],
        "user": row[1],
        "server_version": row[2],
        "dsn_without_password": postgres.dsn(include_password=False),
    }
